#!/bin/bash

# Путь к папке с обоями
WALLPAPER_DIR="$HOME/Wallpapers"

# Проверка, существует ли директория
if [ ! -d "$WALLPAPER_DIR" ]; then
    notify-send "Ошибка" "Папка $WALLPAPER_DIR не найдена!"
    exit 1
fi

# Получение списка изображений (png, jpg, jpeg)
WALLPAPERS=$(find "$WALLPAPER_DIR" -maxdepth 1 -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \))

# Проверка, есть ли изображения
if [ -z "$WALLPAPERS" ]; then
    notify-send "Ошибка" "В папке $WALLPAPER_DIR нет изображений!"
    exit 1
fi

# Показ списка обоев в rofi
SELECTED=$(echo "$WALLPAPERS" | while read -r line; do basename "$line"; done | rofi -dmenu -i -p "Choose wallpaper")

# Проверка, выбран ли файл
if [ -n "$SELECTED" ]; then
    WALLPAPER_PATH="$WALLPAPER_DIR/$SELECTED"
    
    # Проверка, существует ли выбранный файл
    if [ -f "$WALLPAPER_PATH" ]; then
	hyprctl hyprpaper unload all
	hyprctl hyprpaper preload "$WALLPAPER_PATH"
	hyprctl hyprpaper wallpaper "eDP-1, $WALLPAPER_PATH"
        # Установка обоев через hyprpaper
	#echo """preload = $WALLPAPER_PATH
#wallpaper = eDP-1, $WALLPAPER_PATH""" > $HOME/.config/hypr/hyprpaper.conf
	# hyprctl reload hyprpaper
	# hyprctl hyprpaper reload ,"$WALLPAPER_PATH"
        # hyprctl hyprpaper preload ,"$WALLPAPER_PATH"
        # hyprctl hyprpaper wallpaper ",$WALLPAPER_PATH"
        notify-send "Обои установлены" "$SELECTED"
    else
        notify-send "Ошибка" "Файл $SELECTED не существует!"
        exit 1
    fi
else
    notify-send "Отмена" "Выбор обоев отменён."
    exit 0
fi


